ULB/urls.py
from django.conf.urls import url, include
from ULB.api.views import FileUploadView, ApiRoot
from rest_framework.response import Response
from rest_framework.reverse import reverse
from ULB import views


urlpatterns = [
    url(r'^api/', include('ULB.api.urls')),
    url(r'^upload-data/$', views.file_upload, name='file-upload-ulb'),
    url(r'^predict/$', views.predict, name='predict'),
]

ifor/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import ListView, DetailView, FormView

from . import views_dataset, views_setLabel, views_fiturImp
from . import views_setFitur, views_eda
from . import views_iForest, views_hyperparameter

app_name = 'ifor'

urlpatterns = [
    
    # path('random-forest/pohon/<int:pk>/<int:no_pohon>',
    #      views_randomForest.get_pohon, name='random-forest-pohon'),
    # path('random-forest/fitur_importance/<int:pk>',
    #      views_randomForest.get_fitur_importance, name='random-forest-fitur-importance'),
    path('iforest/default/<int:pk>',
         views_iForest.set_default, name='iforest-set-default'),
    path('iforest/result/<int:pk>',
         views_iForest.get_result, name='iforest-result'),
    #     path('random-forest/detail-tree/<int:pk>',
    #          views_randomForest.RandomForestDetailTreeView.as_view(), name='random-forest-detail-tree'),
    path('iforest/detail/<int:pk>',
         views_iForest.IForestDetailView.as_view(), name='iforest-detail'),
    path('iforest/delete/<int:pk>',
         views_iForest.IForestDeleteView.as_view(), name='iforest-delete'),
    path('iforest/create/', views_iForest.IForestCreateView.as_view(),
         name='iforest-create'),
    path('iforest/', views_iForest.IForestListView.as_view(),
         name='iforest-index'),

    # -------------------set hyperparameter
    path('hyperparameter/default/<int:pk>',
         views_hyperparameter.set_default, name='hyperparameter-set-default'),
    path('hyperparameter/detail/<int:pk>',
         views_hyperparameter.HyperparameterDetailView.as_view(), name='hyperparameter-detail'),
    path('hyperparameter/update/<int:pk>',
         views_hyperparameter.HyperparameterUpdateView.as_view(), name='hyperparameter-update'),
    path('hyperparameter/delete/<int:pk>',
         views_hyperparameter.HyperparameterDeleteView.as_view(), name='hyperparameter-delete'),
    path('hyperparameter/create/', views_hyperparameter.HyperparameterCreateView.as_view(),
         name='hyperparameter-create'),
    path('hyperparameter/', views_hyperparameter.HyperparameterListView.as_view(),
         name='hyperparameter-index'),

	# -------------------set fitur
    path('set-fitur/default/<int:pk>',
         views_setFitur.set_default, name='set-fitur-set-default'),
    path('set-fitur/detail/<int:pk>',
         views_setFitur.SetFiturDetailView.as_view(), name='set-fitur-detail'),
    path('set-fitur/update/<int:pk>',
         views_setFitur.SetFiturUpdateView.as_view(), name='set-fitur-update'),
    path('set-fitur/delete/<int:pk>',
         views_setFitur.SetFiturDeleteView.as_view(), name='set-fitur-delete'),
    path('set-fitur/create/', views_setFitur.SetFiturCreateView.as_view(),
         name='set-fitur-create'),
    path('set-fitur/', views_setFitur.SetFiturListView.as_view(),
         name='set-fitur-index'),

	# -------------------EDA

    path('eda/pca/',
         views_eda.pca, name='eda-pca'),
    path('eda/plot/<int:pk>/boxplot/<str:list_fitur>',
         views_eda.get_boxplot, name='eda-plot-get-boxplot'),
    # path('eda/detail/<int:pk>/boxplot',
    #      views_eda.boxplot, name='eda-detail-boxplot'),
    # path('eda/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_eda.get_swarm_box, name='eda-detail-swarm-box'),
    path('eda/plot/<str:list_fitur>',
         views_eda.plot, name='eda-plot'),
    path('eda/eksplore-data/',
         views_eda.eksploreData, name='eda-eksplore-data'),

    # -------------------fitur Importance
    path('fiturImp/', views_fiturImp.FiturImpListView.as_view(),
         name='fiturImp-index'),
    path('fiturImp/detail/<int:pk>',
         views_fiturImp.FiturImpDetailView.as_view(), name='fiturImp-detail'),
    path('fiturImp/create/', views_fiturImp.FiturImpCreateView.as_view(),
         name='fiturImp-create'),

    # -------------------set label
    path('set-label/create/label-fraud/<int:id_dataset>/<str:kolom_label>',
         views_setLabel.get_label_fraud, name='set-label-get-label-fraud'),
    path('set-label/create/label/<int:id_dataset>',
         views_setLabel.get_label, name='set-label-get-label'),
    path('set-label/default/<int:pk>',
         views_setLabel.set_default, name='set-label-set-default'),
    path('set-label/detail/<int:pk>',
         views_setLabel.SetLabelDetailView.as_view(), name='set-label-detail'),
    path('set-label/update/<int:pk>',
         views_setLabel.SetLabelUpdateView.as_view(), name='set-label-update'),
    path('set-label/delete/<int:pk>',
         views_setLabel.SetLabelDeleteView.as_view(), name='set-label-delete'),
    path('set-label/create/', views_setLabel.SetLabelCreateView.as_view(),
         name='set-label-create'),
    path('set-label/', views_setLabel.SetLabelListView.as_view(),
         name='set-label-index'),

    # -------------------dataset
    path('dataset/default/<int:pk>',
         views_dataset.set_default, name='dataset-set-default'),
    # path('dataset/detail/<int:pk>/boxplot/<str:list_fitur>',
    #      views_dataset.get_boxplot, name='dataset-detail-get-boxplot'),
    # path('dataset/detail/<int:pk>/boxplot',
    #      views_dataset.boxplot, name='dataset-detail-boxplot'),
    # path('dataset/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_dataset.get_swarm_box, name='dataset-detail-swarm-box'),
    path('dataset/detail/<int:pk>',
         views_dataset.DatasetDetailView.as_view(), name='dataset-detail'),
    path('dataset/update/<int:pk>',
         views_dataset.DatasetUpdateView.as_view(), name='dataset-update'),
    path('dataset/delete/<int:pk>',
         views_dataset.DatasetDeleteView.as_view(), name='dataset-delete'),
    path('dataset/create/', views_dataset.DatasetCreateView.as_view(),
         name='dataset-create'),
    path('dataset/', views_dataset.DatasetListView.as_view(), name='dataset-index'),
]

random_forest/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import ListView, DetailView, FormView

from . import views_dataset, views_setLabel
from . import views_setFitur, views_hyperparameterRF
from . import views_randomForest, views_eda

app_name = 'random_forest'

urlpatterns = [
    path('random-forest/default/<int:pk>',
         views_randomForest.set_default, name='random-forest-set-default'),
    path('random-forest/pohon/<int:pk>/<int:no_pohon>',
         views_randomForest.get_pohon, name='random-forest-pohon'),
    path('random-forest/fitur_importance/<int:pk>',
         views_randomForest.get_fitur_importance, name='random-forest-fitur-importance'),
    path('random-forest/result/<int:pk>',
         views_randomForest.get_result, name='random-forest-result'),
    #     path('random-forest/detail-tree/<int:pk>',
    #          views_randomForest.RandomForestDetailTreeView.as_view(), name='random-forest-detail-tree'),
    path('random-forest/detail/<int:pk>',
         views_randomForest.RandomForestDetailView.as_view(), name='random-forest-detail'),
    path('random-forest/delete/<int:pk>',
         views_randomForest.RandomForestDeleteView.as_view(), name='random-forest-delete'),
    path('random-forest/create/', views_randomForest.RandomForestCreateView.as_view(),
         name='random-forest-create'),
    path('random-forest/', views_randomForest.RandomForestListView.as_view(),
         name='random-forest-index'),

    # -------------------set hyperparameter RF
    path('hyperparameter-RF/default/<int:pk>',
         views_hyperparameterRF.set_default, name='hyperparameter-RF-set-default'),
    path('hyperparameter-RF/detail/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDetailView.as_view(), name='hyperparameter-RF-detail'),
    path('hyperparameter-RF/update/<int:pk>',
         views_hyperparameterRF.HyperparameterRFUpdateView.as_view(), name='hyperparameter-RF-update'),
    path('hyperparameter-RF/delete/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDeleteView.as_view(), name='hyperparameter-RF-delete'),
    path('hyperparameter-RF/create/', views_hyperparameterRF.HyperparameterRFCreateView.as_view(),
         name='hyperparameter-RF-create'),
    path('hyperparameter-RF/', views_hyperparameterRF.HyperparameterRFListView.as_view(),
         name='hyperparameter-RF-index'),

    # -------------------set fitur
    path('set-fitur/default/<int:pk>',
         views_setFitur.set_default, name='set-fitur-set-default'),
    path('set-fitur/detail/<int:pk>',
         views_setFitur.SetFiturDetailView.as_view(), name='set-fitur-detail'),
    path('set-fitur/update/<int:pk>',
         views_setFitur.SetFiturUpdateView.as_view(), name='set-fitur-update'),
    path('set-fitur/delete/<int:pk>',
         views_setFitur.SetFiturDeleteView.as_view(), name='set-fitur-delete'),
    path('set-fitur/create/', views_setFitur.SetFiturCreateView.as_view(),
         name='set-fitur-create'),
    path('set-fitur/', views_setFitur.SetFiturListView.as_view(),
         name='set-fitur-index'),

    # -------------------EDA
    path('eda/pca/',
         views_eda.pca, name='eda-pca'),
    path('eda/plot/<int:pk>/boxplot/<str:list_fitur>',
         views_eda.get_boxplot, name='eda-plot-get-boxplot'),
    # path('eda/detail/<int:pk>/boxplot',
    #      views_eda.boxplot, name='eda-detail-boxplot'),
    # path('eda/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_eda.get_swarm_box, name='eda-detail-swarm-box'),
    path('eda/plot/<str:list_fitur>',
         views_eda.plot, name='eda-plot'),
    path('eda/eksplore-data/',
         views_eda.eksploreData, name='eda-eksplore-data'),

    # -------------------set label
    path('set-label/create/label-kanker/<int:id_dataset>/<str:kolom_label>',
         views_setLabel.get_label_kanker, name='set-label-get-label-kanker'),
    path('set-label/create/label/<int:id_dataset>',
         views_setLabel.get_label, name='set-label-get-label'),
    path('set-label/default/<int:pk>',
         views_setLabel.set_default, name='set-label-set-default'),
    path('set-label/detail/<int:pk>',
         views_setLabel.SetLabelDetailView.as_view(), name='set-label-detail'),
    path('set-label/update/<int:pk>',
         views_setLabel.SetLabelUpdateView.as_view(), name='set-label-update'),
    path('set-label/delete/<int:pk>',
         views_setLabel.SetLabelDeleteView.as_view(), name='set-label-delete'),
    path('set-label/create/', views_setLabel.SetLabelCreateView.as_view(),
         name='set-label-create'),
    path('set-label/', views_setLabel.SetLabelListView.as_view(),
         name='set-label-index'),

    # -------------------dataset
    path('dataset/default/<int:pk>',
         views_dataset.set_default, name='dataset-set-default'),
    # path('dataset/detail/<int:pk>/boxplot/<str:list_fitur>',
    #      views_dataset.get_boxplot, name='dataset-detail-get-boxplot'),
    # path('dataset/detail/<int:pk>/boxplot',
    #      views_dataset.boxplot, name='dataset-detail-boxplot'),
    # path('dataset/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_dataset.get_swarm_box, name='dataset-detail-swarm-box'),
    path('dataset/detail/<int:pk>',
         views_dataset.DatasetDetailView.as_view(), name='dataset-detail'),
    path('dataset/update/<int:pk>',
         views_dataset.DatasetUpdateView.as_view(), name='dataset-update'),
    path('dataset/delete/<int:pk>',
         views_dataset.DatasetDeleteView.as_view(), name='dataset-delete'),
    path('dataset/create/', views_dataset.DatasetCreateView.as_view(),
         name='dataset-create'),
    path('dataset/', views_dataset.DatasetListView.as_view(), name='dataset-index'),


    #     path('detail/<int:id_buku>', views.detail, name='detail'),
    #     path('update/<int:id_buku>', views.update, name='update'),
    #     path('delete/<int:id_buku>', views.delete, name='delete'),
    #     path('create-file/', views.create_file, name='create-file'),
    #     path('create/', views.create, name='create'),
    #     path('', views.index, name='index'),

]

rootweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home-ss3'),
    path('admin/', admin.site.urls),
    path('RF/', include('random_forest.urls', namespace='rf')),
    path('IF/', include('ifor.urls', namespace='if')),
    url(r'^ulb/', include('ULB.urls')),
    path('RF/home/', views.index, name='home-rf'),
    path('IF/home/', views.indexIF, name='home-if'),
    url(r'^datatests/', views.DatasetListView.as_view(), name='datatest-view'),
    path('settings/', views.settings, name='settings'),
    path('import/<int:pk>/', views.importDb, name='importDb'),
    path('pickle/<str:choice>/', views.setpickle, name='set_pickle'),
    path('changeState/<int:pk>/', views.changeState, name='changeState')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ifor/models.py
from django.db import models

# Create your models here.

ifor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views import View
from django.core.files.storage import FileSystemStorage

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import os
import matplotlib.pyplot as plt
import math
import collections
import time

import os

from django.utils.deconstruct import deconstructible



def dataframe(file_dataset, separator):
    pd.set_option('colheader_justify', 'center')
    df = pd.DataFrame()
    if separator == 'koma':
        df = pd.read_csv(file_dataset, sep=',')
    elif separator == 'titik_koma':
        df = pd.read_csv(file_dataset, sep=';')
    elif separator == 'tab':
        df = pd.read_csv(file_dataset, sep='\t')
    elif separator == 'enter':
        df = pd.read_csv(file_dataset, sep='\n')

    return df



# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    #how many correct predictions?
    correct = 0
    #for each actual label
    for i in range(len(actual)):
        #if actual matches predicted label
        if actual[i] == predicted[i]:
            #add 1 to the correct iterator
            correct += 1
    #return percentage of predictions that were correct
    return correct / float(len(actual)) * 100.0

    
@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format('ifor_'+filename.split('.')[0], ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

def rename_and_path(jenis):
    return PathAndRename(jenis)

ifor/templates/ifor/dataset/detail_swarm_box.html
{% extends 'templatesIF.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    <link rel="stylesheet" href="{% static 'random_forest/css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'vendor/select-picker/bootstrap-select.min.css' %}">

{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  <a class="btn btn-secondary" href="{% url 'if:random-forest-index' %} ">
                    <i class='mdi mdi-keyboard-backspace'></i> Semua {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
    <br>
        <div class="text-center mb-4" >
          <a class="btn btn-info" href='{% url 'rf:dataset-detail' dataset.id %}'>
              View Detail &nbsp;
              <i class='mdi mdi-timetable' ></i> 
          </a>
          <a class="btn alert-secondary" href="#">
              View Swarm-Box Plot &nbsp;
              <i class='mdi mdi-chart-scatterplot-hexbin' ></i> 
          </a>
          <a class="btn btn-info" href="{% url 'rf:dataset-detail-swarm-box' dataset.id 'default' %}">
              View Pair Plot &nbsp;
              <i class='mdi mdi-chart-areaspline' ></i> 
          </a>
        </div>
        <div class="card">
            <div class="card-header text-center alert-warning">
                  <div class="form-group">
                    <label for="list_fitur">PIlih Nomor Pohon :</label>
                    <select name="list_fitur" id="list_fitur" title='--pilih--' multiple class='selectpicker' data-live-search='true' data-width='100%'>
                      <option value="">--Pilih Pohon--</option>
                    </select>                       
                  </div>
                  <a id="submit-plot" class="btn btn-success" href="{% url 'rf:dataset-detail-swarm-box' dataset.id 'default' %}" title='{{dataset}}'>
                    Submit
                  </a>
            </div>
            <div class="card-body">
              {% comment %} <iframe src="{% url 'rf:dataset-detail-boxplot' dataset.pk%}" frameborder="0" height="500px" width="100%"></iframe> {% endcomment %}
              <iframe src="{{url_plot}}" frameborder="0" height="500px" width="100%">{{url_plot}}</iframe>

              {% comment %} <h5>Pohon ke-{{list_fitur}}</h5>
              <embed src="{% static 'random_forest/tree/tree.pdf' %}" type="application/pdf" width="100%" height="750px" class="responsive">
              
              <a href="{% static 'random_forest/tree/tree.pdf' %}">download</a> {% endcomment %}
            </div>
        </div>
        

    </div>

{% endblock content %}

{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    <script src="{% static 'random_forest/js/script.js' %}"></script>
    <script src="{% static 'vendor/select-picker/bootstrap-select.min.js' %}"></script>

    <script>
        (function($) {
        'use strict';
            $(function() {
                //$( "#dataset" ).addClass('active');
                $("#dataset").addClass('active');
                $("#submit-plot").hide();

                $('#list_fitur').find('option').remove();
                {% for i in fitur %}
                  $('#list_fitur').append('<option value="{{i}}">{{i}}</option>');
                {% endfor %}

                $('#list_fitur').change(function(){
                    var list_fitur = $('#list_fitur').val();
                    if (list_fitur == '') {
                      $("#submit-plot").hide();

                    }else{
                      $("#submit-plot").show();
                    }

                });
                
                $('body').on('click', '#submit-plot', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title');
                  var list_fitur = $('#list_fitur').val();
                  url = url.replace('default',list_fitur)

                  window.location.replace(url);
                });

            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

ifor/templates/ifor/dataset/index.html
{% extends 'templatesIF.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %} "> {% endcomment %}
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}

    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  <a class="btn btn-success" href="{% url 'if:dataset-create' %} ">
                    <i class='mdi mdi-plus-circle-outline'></i> Tambah
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
              <div class="card">
                <div class="card-header alert-warning" >
                  <h6> <u> Perhatian </u>: pastikan memilih separator sesuai dengan format file .csv </h6>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="coba" class="table">
                      <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th width="10%">Set Default</th>
                            <th>Nama</th>
                            <th>Deskripsi</th>
                            <th width="7%">File</th>
                            <th width="13%">Kelola</th>
                        </tr>
                      </thead>
                      <tbody>
                            
                            {% for dataset in datasets %}
                              <tr>
                                <td class='text-center'>{{forloop.counter}} </td>
                                <td>
                                  {% if dataset.default_dataset == False %}
                                     <a id="set-default-dataset" class="btn btn-info use-dataset" href="{% url 'if:dataset-set-default' dataset.id %}" title='set default dataset {{dataset}}'>
                                    Tidak
                                  {% else %}
                                     <a class="btn btn-secondary use-dataset" href="#" title='set default dataset {{dataset}}'>
                                    Ya
                                  {% endif %}
                                    {% comment %} {{dataset.default_dataset}}                                   {% endcomment %}
                                      <i class="mdi mdi-lock-open-outline" style="zoom:1.5"></i>
                                    </a>
                                </td>
                                <td>{{dataset.nama}} </td>
                                <td>{{dataset.deskripsi|truncatechars:50}}</td>
                                <td>
                                    <a class="btn btn-success" href="{{dataset.file_dataset.url}}" target='__blank' title='download file {{dataset.nama}}'><i class="mdi mdi-folder-download text-white"></i></a>
                                </td>
                                <td>
                                  {% if dataset.set_label == True %}
                                    <a class="btn btn-primary" href="{% url 'if:dataset-detail' dataset.id %}" title='detail {{dataset.nama}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                    <a class="btn btn-secondary" href="#" title='edit {{dataset.nama}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                    <a class="btn btn-secondary" href="#" title='hapus {{dataset.nama}}'><i class="mdi mdi-delete-forever"></i></a>
                                  {% else %}
                                    <a class="btn btn-primary" href="{% url 'if:dataset-detail' dataset.id %}" title='detail {{dataset.nama}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                    <a class="btn btn-warning" href="{% url 'if:dataset-update' dataset.id %}" title='edit {{dataset.nama}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                    <a id="delete-data" class="btn btn-danger" href="{% url 'if:dataset-delete' dataset.id %}" title='hapus {{dataset.nama}}'><i class="mdi mdi-delete-forever"></i></a>
                                  {% endif %}

                                </td>
                              </tr>        
                            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

    </div>
{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'buku/js/script.js' %}"></script> {% endcomment %}
    <script>
    (function($) {
        'use strict';
        $(function() {
            $("#dataset").addClass('active');
            
            $('#coba').DataTable({
                "aLengthMenu": [
                    [5, 10, 15, -1],
                    [5, 10, 15, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: "search : "
                },
                searching: true, paging: true, info: true
            });

            {% if messages %}
              {% for message in messages %}
                swal({
                  type: 'success',
                  title: 'Berhasil!',
                  text: '{{message}}',
                  timer: 2500
                });
              {% endfor %}
            {% endif %}

            // action add update

              // delete
              $('body').on('click', '#delete-data', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin menghapus ' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Hapus',
                      cancelButtonText: 'Batal'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              setTimeout(function () { location.reload();}, 2600);
                              swal({
                                  type: 'success',
                                  title: 'Success!',
                                  text: 'Data ' + '"'+ title +'"'+ ' berhasil dihapus!',
                                  timer: 2500

                              });
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Oops...',
                                  text: 'Something went wrong!'
                              });
                          }
                      });
                  }
                  });
              });

              // set default
              $('body').on('click', '#set-default-dataset', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin melakukan ' + '"'+ title +'" sebagai dataset default ',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      cancelButtonText: 'Batal',
                      confirmButtonText: 'Submit'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              if (response == 'success') {
                                setTimeout(function () { location.reload();}, 2600);
                                swal({
                                    type: 'success',
                                    title: 'Success!',
                                    text: '"'+ title +'"'+ ' berhasil diatur sebagai dataset default!',
                                    timer: 2500
                                });
                              }else {
                                swal({
                                  type: response,
                                  title: 'Periksa kembali separator file .csv',
                                  text: '"--pastikan kembali dengan melihat menu detail--"'
                              });
                              }
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Periksa kembali separator file .csv',
                                  text: '"--pastikan kembali dengan melihat menu detail--"'
                              });
                          }
                      });
                  }
                  });
              });

        });
    })(jQuery);
    </script>
{% endblock app_scripts %}