ULB/urls.py
from django.conf.urls import url, include
from ULB.api.views import FileUploadView, ApiRoot
from rest_framework.response import Response
from rest_framework.reverse import reverse
from ULB import views


urlpatterns = [
    url(r'^api/', include('ULB.api.urls')),
    url(r'^upload-data/$', views.file_upload, name='file-upload-ulb'),
    url(r'^predict/$', views.predict, name='predict'),
]

random_forest/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import ListView, DetailView, FormView

from . import views_dataset, views_setLabel
from . import views_setFitur, views_hyperparameterRF
from . import views_randomForest, views_eda

app_name = 'random_forest'

urlpatterns = [
    path('random-forest/default/<int:pk>',
         views_randomForest.set_default, name='random-forest-set-default'),
    path('random-forest/pohon/<int:pk>/<int:no_pohon>',
         views_randomForest.get_pohon, name='random-forest-pohon'),
    path('random-forest/fitur_importance/<int:pk>',
         views_randomForest.get_fitur_importance, name='random-forest-fitur-importance'),
    path('random-forest/result/<int:pk>',
         views_randomForest.get_result, name='random-forest-result'),
    #     path('random-forest/detail-tree/<int:pk>',
    #          views_randomForest.RandomForestDetailTreeView.as_view(), name='random-forest-detail-tree'),
    path('random-forest/detail/<int:pk>',
         views_randomForest.RandomForestDetailView.as_view(), name='random-forest-detail'),
    path('random-forest/delete/<int:pk>',
         views_randomForest.RandomForestDeleteView.as_view(), name='random-forest-delete'),
    path('random-forest/create/', views_randomForest.RandomForestCreateView.as_view(),
         name='random-forest-create'),
    path('random-forest/', views_randomForest.RandomForestListView.as_view(),
         name='random-forest-index'),

    # -------------------set hyperparameter RF
    path('hyperparameter-RF/default/<int:pk>',
         views_hyperparameterRF.set_default, name='hyperparameter-RF-set-default'),
    path('hyperparameter-RF/detail/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDetailView.as_view(), name='hyperparameter-RF-detail'),
    path('hyperparameter-RF/update/<int:pk>',
         views_hyperparameterRF.HyperparameterRFUpdateView.as_view(), name='hyperparameter-RF-update'),
    path('hyperparameter-RF/delete/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDeleteView.as_view(), name='hyperparameter-RF-delete'),
    path('hyperparameter-RF/create/', views_hyperparameterRF.HyperparameterRFCreateView.as_view(),
         name='hyperparameter-RF-create'),
    path('hyperparameter-RF/', views_hyperparameterRF.HyperparameterRFListView.as_view(),
         name='hyperparameter-RF-index'),

    # -------------------set fitur
    path('set-fitur/default/<int:pk>',
         views_setFitur.set_default, name='set-fitur-set-default'),
    path('set-fitur/detail/<int:pk>',
         views_setFitur.SetFiturDetailView.as_view(), name='set-fitur-detail'),
    path('set-fitur/update/<int:pk>',
         views_setFitur.SetFiturUpdateView.as_view(), name='set-fitur-update'),
    path('set-fitur/delete/<int:pk>',
         views_setFitur.SetFiturDeleteView.as_view(), name='set-fitur-delete'),
    path('set-fitur/create/', views_setFitur.SetFiturCreateView.as_view(),
         name='set-fitur-create'),
    path('set-fitur/', views_setFitur.SetFiturListView.as_view(),
         name='set-fitur-index'),

    # -------------------EDA
    path('eda/pca/',
         views_eda.pca, name='eda-pca'),
    path('eda/plot/<int:pk>/boxplot/<str:list_fitur>',
         views_eda.get_boxplot, name='eda-plot-get-boxplot'),
    # path('eda/detail/<int:pk>/boxplot',
    #      views_eda.boxplot, name='eda-detail-boxplot'),
    # path('eda/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_eda.get_swarm_box, name='eda-detail-swarm-box'),
    path('eda/plot/<str:list_fitur>',
         views_eda.plot, name='eda-plot'),
    path('eda/eksplore-data/',
         views_eda.eksploreData, name='eda-eksplore-data'),

    # -------------------set label
    path('set-label/create/label-kanker/<int:id_dataset>/<str:kolom_label>',
         views_setLabel.get_label_kanker, name='set-label-get-label-kanker'),
    path('set-label/create/label/<int:id_dataset>',
         views_setLabel.get_label, name='set-label-get-label'),
    path('set-label/default/<int:pk>',
         views_setLabel.set_default, name='set-label-set-default'),
    path('set-label/detail/<int:pk>',
         views_setLabel.SetLabelDetailView.as_view(), name='set-label-detail'),
    path('set-label/update/<int:pk>',
         views_setLabel.SetLabelUpdateView.as_view(), name='set-label-update'),
    path('set-label/delete/<int:pk>',
         views_setLabel.SetLabelDeleteView.as_view(), name='set-label-delete'),
    path('set-label/create/', views_setLabel.SetLabelCreateView.as_view(),
         name='set-label-create'),
    path('set-label/', views_setLabel.SetLabelListView.as_view(),
         name='set-label-index'),

    # -------------------dataset
    path('dataset/default/<int:pk>',
         views_dataset.set_default, name='dataset-set-default'),
    # path('dataset/detail/<int:pk>/boxplot/<str:list_fitur>',
    #      views_dataset.get_boxplot, name='dataset-detail-get-boxplot'),
    # path('dataset/detail/<int:pk>/boxplot',
    #      views_dataset.boxplot, name='dataset-detail-boxplot'),
    # path('dataset/detail-swarm-box/<int:pk>/<str:list_fitur>',
    #      views_dataset.get_swarm_box, name='dataset-detail-swarm-box'),
    path('dataset/detail/<int:pk>',
         views_dataset.DatasetDetailView.as_view(), name='dataset-detail'),
    path('dataset/update/<int:pk>',
         views_dataset.DatasetUpdateView.as_view(), name='dataset-update'),
    path('dataset/delete/<int:pk>',
         views_dataset.DatasetDeleteView.as_view(), name='dataset-delete'),
    path('dataset/create/', views_dataset.DatasetCreateView.as_view(),
         name='dataset-create'),
    path('dataset/', views_dataset.DatasetListView.as_view(), name='dataset-index'),


    #     path('detail/<int:id_buku>', views.detail, name='detail'),
    #     path('update/<int:id_buku>', views.update, name='update'),
    #     path('delete/<int:id_buku>', views.delete, name='delete'),
    #     path('create-file/', views.create_file, name='create-file'),
    #     path('create/', views.create, name='create'),
    #     path('', views.index, name='index'),

]

rootweb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home-ss3'),
    path('admin/', admin.site.urls),
    path('RF/', include('random_forest.urls', namespace='rf')),
    path('IF/', include('ifor.urls', namespace='if')),
    url(r'^ulb/', include('ULB.urls')),
    path('RF/home/', views.index, name='home-rf'),
    path('IF/home/', views.indexIF, name='home-if'),
    url(r'^datatests/', views.DatasetListView.as_view(), name='datatest-view'),
    path('settings/', views.settings, name='settings'),
    path('import/<int:pk>/', views.importDb, name='importDb'),
    path('pickle/<str:choice>/', views.setpickle, name='set_pickle'),
    path('changeState/<int:pk>/', views.changeState, name='changeState')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

random_forest/models.py
from django.db import models
from django.utils.text import slugify


# def validate_file_extension(value):
#     import os
#     from django.core.exceptions import ValidationError
#     ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
#     valid_extensions = ['.pdf']
#     if not ext.lower() in valid_extensions:
#         raise ValidationError(u'Unsupported file extension.only PDF files')


# class Buku(models.Model):
#     title = models.CharField(max_length=255)
#     author = models.CharField(max_length=255)
#     file_data = models.FileField(
#         upload_to='buku/pdf/', validators=[validate_file_extension])
#     cover = models.ImageField(upload_to='buku/cover/', null=True, blank=True)

#     def delete(self, *args, **kwargs):
#         self.file_data.delete()
#         self.cover.delete()
#         super().delete(*args, **kwargs)

#     def __str__(self):
#         return "[{}] {}".format(self.id, self.title)

random_forest/forms.py
# membuat form
from django import forms

from .models import Buku as BukuModel


# class BukuForm(forms.ModelForm):
#     class Meta:
#         model = BukuModel
#         fields = (
#             'title',
#             'author',
#             'file_data',
#             'cover'
#         )

#         labels = {
#             'author': 'Penulis',
#             'file_data': 'File',
#             'cover': 'Sampul Buku',
#         }

#         widgets = {
#             'title': forms.TextInput(
#                 attrs={
#                     'class': 'form-control',
#                     'placeholder': 'judul buku',
#                 }
#             ),
#             'author': forms.TextInput(
#                 attrs={
#                     'class': 'form-control',
#                     'placeholder': 'nama penulis',
#                 }
#             ),
#             'file_data': forms.ClearableFileInput(
#                 attrs={
#                     'class': 'form-control',
#                 }
#             ),
#             'cover': forms.ClearableFileInput(
#                 attrs={
#                     'class': 'form-control',
#                 }
#             ),

#         }

random_forest/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views import View
from django.core.files.storage import FileSystemStorage
from sklearn.model_selection import train_test_split

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import os
import matplotlib.pyplot as plt
import seaborn as sns
import math
import collections
import time


def dataframe(file_dataset, separator):
    pd.set_option('colheader_justify', 'center')
    df = pd.DataFrame()
    if separator == 'koma':
        df = pd.read_csv(file_dataset, sep=',')
    elif separator == 'titik_koma':
        df = pd.read_csv(file_dataset, sep=';')
    elif separator == 'tab':
        df = pd.read_csv(file_dataset, sep='\t')
    elif separator == 'enter':
        df = pd.read_csv(file_dataset, sep='\n')

    return df


def cross_val_split(X, fold=2, seed=0):
    np.random.seed(seed)
    n_folds = fold
    size = X.shape[0]/n_folds
    X_idx = list(range(X.shape[0]))
    folds_data = []
    for i in range(n_folds):
        #         print(X_idx)
        random_idx = list(np.random.choice(X_idx, int(size), replace=False))
#         print(random_idx)
        X_idx = [idx for idx in X_idx if idx not in random_idx]
#         print(X_idx)

        folds_data.append(random_idx)
#         print("--")
    return folds_data

def confussion_matrik(actual,predict):
    TP,FP,FN,TN = 0,0,0,0
    for i,val in enumerate(actual):
        if val == 0:
            if val == predict[i]:
                TN += 1
            else:
                FP += 1
        if val == 1:
            if val == predict[i]:
                TP += 1
            else:
                FN += 1
    return TP,FP,FN,TN
 
def acc_sens_spec(actual,predict):
    TP,FP,FN,TN = confussion_matrik(actual,predict)
    accuracy,sensitivity,specifity = 0,0,0
    if (TP+FP+FN+TN) > 0 :
        accuracy = (TP+TN)/(TP+FP+FN+TN)
    if (TP+FN) > 0 :
        sensitivity = TP/(TP+FN)
    if (TN +FP) > 0 :
        specifity = TN/(TN +FP)
    
    return accuracy,sensitivity,specifity

# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    #how many correct predictions?
    correct = 0
    #for each actual label
    for i in range(len(actual)):
        #if actual matches predicted label
        if actual[i] == predicted[i]:
            #add 1 to the correct iterator
            correct += 1
    #return percentage of predictions that were correct
    return correct / float(len(actual)) * 100.0

def kfold_cross_validation(model, X, y, n_fold=2, n_seed=0):
    folds = cross_val_split(X, fold=n_fold, seed=n_seed)
    fold_result = []
    for i in range(len(folds)):
        #     print(i)
        train = []
        for j in range(len(folds)):
            if j != i:
                train = train + folds[j]
        test = folds[i]

        X_train = X.iloc[train, :].reset_index(drop=True)
        y_train = y[train].reset_index(drop=True)

        X_test = X.iloc[test, :].reset_index(drop=True)
        y_test = y[test].reset_index(drop=True)

        t0 = time.time()
        model.fit(X_train, y_train)
        t1 = time.time()
        waktu = t1 - t0

        predict = model.predict(X_test)
        accuracy, sensitivity, specifity = acc_sens_spec(y_test, predict)

        result = [accuracy, sensitivity, specifity, waktu]
        fold_result.append(result)

    return fold_result

def prec_rec_f1score(file_cm,actual,predict):
    TP,FP,FN,TN = confussion_matrik(actual,predict)

    df_heatmap = pd.DataFrame([[TP,FN],[FP,TN]],['Aktual Fraud','Aktual Normal'],['Prediksi Fraud','Prediksi Normal'])
    plt.figure(figsize=(8,8))
    plot = sns.set(font_scale =1.4)
    plot = sns.heatmap(df_heatmap,annot=True, annot_kws={'size':16},fmt='g')

    figure = plot.get_figure() 
    figure.savefig(file_cm)
    print(file_cm)
    # figure.savefig("coba.png")


    accuracy,sensitivity,specifity = 0,0,0
# precision
    if (TP+FP) == 0 :
        precision = 0
    else :
        precision = TP/(TP+FP)

# recall
    if (TP+FN) == 0 :
        recall = 0
    else :
        recall = TP/(TP+FN)

# f1_score
    if (precision+recall) == 0 :
        f1_score = 0
    else :
        f1_score = 2*((precision*recall)/(precision+recall))

    
    return precision,recall,f1_score

def train_test_validation(file_cm, model, X, y, prosentase=30, n_seed=0):
    end_result =[]
    prosentase_dec = prosentase / 100
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=prosentase_dec, random_state=n_seed,stratify=y)
    print(X_train.shape)
    print(X_test.shape)

    model.fit(X_train, y_train)
    predict = model.predict(X_test)

    precision, recall, f1_score = prec_rec_f1score(file_cm, y_test, predict)

    result = [precision, recall, f1_score]
    end_result.append(result)

    return end_result

random_forest/templates/random_forest/setLabel/detail.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    <link rel="stylesheet" href="{% static 'random_forest/css/style.css' %} ">
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  <a class="btn btn-secondary" href="{% url 'rf:set-label-index' %} ">
                    <i class='mdi mdi-keyboard-backspace'></i> Semua {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
    <br>
        <div class="card">
            <div class="card-header">
                <h2>{{setlabel.dataset.nama}} </h2>
                <p><u>Separator</u> : {{setlabel.dataset.separator}} </p>
                <p><u>Deskripsi</u> : {{setlabel.dataset.deskripsi}} </p>
               <a class="btn btn-primary" href="{% url 'rf:dataset-detail' setlabel.dataset.id %}" target='__blank' title='download file {{setlabel.dataset}}'>View Dataset Detail <i class="mdi mdi-file-export text-white"></i></a>
                                  
            </div>
            <div class="card-body">
                <table border='0' style='font-size : 14px' class='table table-striped'>
                    <tr>
                        <th width='18%'>Atribut</th>
                        <th width='3%' class='text-center'>|</th>
                        <th>Nilai</th>
                    </tr>                
                    <tr>
                        <td>Kolom label (y)</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{setlabel.kolom_label}}</td>
                    </tr>
                    <tr>
                        <td>Nilai label/kelas</td>
                        <td width='5%' class='text-center'> : </td>
                        <td> {{label}}</td>
                    </tr>
                    <tr>
                        <td>Frekuensi label/kelas</td>
                        <td width='5%' class='text-center'> : </td>
                        <td> {{count}}</td>
                    </tr>
                    <tr>
                        <td>Nilai label kelas fraud</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{setlabel.nilai_label_fraud}}</td>
                    </tr>
                </table>
                
            </div>
        </div>
        {% comment %}  DF DESCRIBE{% endcomment %}
        <div class="card">
            <div class="card-header">
            </div>
            <div class="card-body">
                {% comment %} <img src="{% url 'rf:set-label-detail-boxplot' dataset.pk%}" alt="boxplot"> {% endcomment %}
                {% comment %} <iframe src="{% url 'rf:set-label-detail-boxplot' dataset.pk%}" frameborder="0" height="500px" width="100%"></iframe> {% endcomment %}
            </div>
        </div>

    </div>

{% endblock content %}

{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    <script src="{% static 'random_forest/js/script.js' %}"></script>
    <script>
        (function($) {
        'use strict';
            $(function() {
                $("#set-label").addClass('active');

                $('.dataframe-style').attr('border',0)
                $('.dataframe-style-2').attr('border',0)
                $('.dataframe-style').DataTable({
                  "aLengthMenu": [
                      [5, 10, 15, -1],
                      [5, 10, 15, "All"]
                  ],
                  "iDisplayLength": 5,
                  "language": {
                      search: "search : "
                  },
                  searching: true, paging: true, info: true
              });
                $('.dataframe-style-2').DataTable({
                  "aLengthMenu": [
                      [5, 10, 15, -1],
                      [5, 10, 15, "All"]
                  ],
                  "iDisplayLength": 10,
                  "language": {
                      search: "search : "
                  },
                  searching: true, paging: true, info: true
              });

            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

random_forest/templates/random_forest/setLabel/index.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'random_forest/css/style.css' %} "> {% endcomment %}
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}

    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                {% if count_default_dataset == 1  %}
                  {% if count_setlabel == 0 %}
                  <a class="btn btn-success" href="{% url 'rf:set-label-create' %} ">
                    <i class='mdi mdi-plus-circle-outline'></i> Tambah 
                  </a>
                  {% else %}
                  <a class="btn btn-secondary" href="# ">
                    <i class='mdi mdi-plus-circle-outline'></i> Tambah 
                  </a>
                  {% endif %}
                {% endif %}

                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
              <div class="card">
                {% if count_default_dataset == 1 %}
                <div class="card-header alert-warning" >
                  <h6> <u> Perhatian </u>: label hanya berisi <i>Binary Class</i> (misal: Normal dan Fraud). Pastikan memilih kolom label dan nilai label fraud dengan benar  </h6>
                </div>              
                {% endif %}
                <div class="card-body">
                  {% if count_default_dataset == 0 %}
                    <div class="text-center">
                      <a class="btn btn-danger"  href="{% url 'rf:dataset-index' %}">
                        <i class="mdi mdi-lock-open-outline"></i>
                        <span class="menu-title">Silahkan Memilih Default Dataset Terlebih Dahulu</span>
                      </a>
                    </div>
                  {% else %}
                    <div class="table-responsive">
                      <table id="coba" class="table">
                        <thead>
                          <tr>
                              <th width="5%">No</th>
                              <th width="7%">Validasi Label</th>
                              <th>Dataset</th>
                              <th>Target</th>
                              <th width="20%">Target kelas Fraud</th>
                              <th width="13%">Kelola</th>
                          </tr>
                        </thead>
                        <tbody>
                              
                              {% for setlabel in setlabels %}
                                <tr>
                                  <td class="text-center">{{forloop.counter}} </td>
                                  <td>
                                    {% if setlabel.validate_label == False %}
                                      <a id="set-default-dataset" class="btn btn-info use-dataset" href="{% url 'rf:set-label-set-default' setlabel.id %}" title='validasi label {{setlabel}}'>
                                      Tidak Tervalidasi
                                    {% else %}
                                      <a class="btn btn-secondary use-dataset" href="#" title='validasi label {{setlabel}}'>
                                      Tervalidasi
                                    {% endif %}
                                    {% comment %} {{setlabel.validate_label}}                                   {% endcomment %}
                                        <i class="mdi mdi-lock-open-outline" style="zoom:1.5"></i>
                                      </a>
                                  </td>
                                  <td>
                                    <a class="btn btn-primary" href="{% url 'rf:dataset-detail' setlabel.dataset.id %}" target='__blank' title='tinjau file dataset {{setlabel.dataset.nama}}'><i class="mdi mdi-file-export text-white"></i></a>
                                      {{setlabel.dataset}} 
                                  </td>
                                  <td>{{setlabel.kolom_label}}</td>
                                  <td>{{setlabel.nilai_label_fraud}}</td>
                                  <td>
                                    {% if setlabel.use_rf == 1 %}
                                      <a class="btn btn-primary" href="{% url 'rf:set-label-detail' setlabel.id %}" title='detail {{setlabel}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                      <a class="btn btn-secondary" href="#" title='edit {{setlabel}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                      <a class="btn btn-secondary" href="#" title='hapus {{setlabel}}'><i class="mdi mdi-delete-forever"></i></a>
                                    {% else %}
                                      <a class="btn btn-primary" href="{% url 'rf:set-label-detail' setlabel.id %}" title='detail {{setlabel}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                      <a class="btn btn-warning" href="{% url 'rf:set-label-update' setlabel.id %}" title='edit {{setlabel}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                      <a id="delete-data" class="btn btn-danger" href="{% url 'rf:set-label-delete' setlabel.id %}" title='hapus {{setlabel}}'><i class="mdi mdi-delete-forever"></i></a>
                                    {% endif %}

                                  </td>
                                </tr>        
                              {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  {% endif %}
                </div>
              </div>

    </div>
{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'buku/js/script.js' %}"></script> {% endcomment %}
    <script>
    (function($) {
        'use strict';
        $(function() {
            $("#set-label").addClass('active');
            
            $('#coba').DataTable({
                "aLengthMenu": [
                    [5, 10, 15, -1],
                    [5, 10, 15, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: "search : "
                },
                searching: true, paging: true, info: true
            });

            {% if messages %}
              {% for message in messages %}
                swal({
                  type: 'success',
                  title: 'Berhasil!',
                  text: '{{message}}',
                  timer: 2500
                });
              {% endfor %}
            {% endif %}

            // action add update

              // delete
              $('body').on('click', '#delete-data', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin menghapus ' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      cancelButtonText: 'Batal',
                      confirmButtonText: 'Hapus'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              setTimeout(function () { location.reload();}, 2600);
                              swal({
                                  type: 'success',
                                  title: 'Success!',
                                  text: 'Data ' + '"'+ title +'"'+ ' berhasil dihapus!',
                                  timer: 2500

                              });
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Oops...',
                                  text: 'Something went wrong!'
                              });
                          }
                      });
                  }
                  });
              });
              // set default
              $('body').on('click', '#set-default-dataset', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin melakukan ' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      cancelButtonText: 'Batal',
                      confirmButtonText: 'Submit'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              if (response == 'success') {
                                setTimeout(function () { location.reload();}, 2600);
                                swal({
                                    type: 'success',
                                    title: 'Success!',
                                    text: '"'+ title +'"'+ ' berhasil',
                                    timer: 2500
                                });
                              }else {
                                swal({
                                  type: response,
                                  title: 'Hanya Binary Kelas',
                                  text: '"--pastikan set nilai kolom label  &  nilai label kelas fraud dengan benar--"'
                              });
                              }
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Hanya Binary Kelas',
                                  text: '"--pastikan set nilai kolom label  &  nilai label kelas fraud dengan benar--"'
                              });
                          }
                      });
                  }
                  });
              });

        });
    })(jQuery);
    </script>
{% endblock app_scripts %}